### ISSUE TITLE
请求去除域名

### ISSUE THREAD

**Issue by StephenSSR** [lingeringsound/10007_auto#10]
您好，black.qimo.ink该域名是为了屏蔽哔哩漫游x停更期间的黑名单检测，但目前哔哩漫游x已恢复并在新版本添加了对该域名检测是否可以访问，所以请求去除对该域名的屏蔽以正常使用新版哔哩漫游x

**Comment by lingeringsound** [comment]
好的，感谢反馈，之前已经去除，但是忘记上传了，抱歉。
