### ISSUE TITLE
大佬你的gitee仓库是关闭了吗

### ISSUE THREAD

**Issue by ChellyL** [lingeringsound/10007_auto#3]
如题，酷安上放出的gitee仓库链接打不开，
以及magisk模块是停止更新了吗

**Comment by lingeringsound** [comment]
差不多吧，Magisk模块基本随缘更新了，没有精力去搞这么多了。

gitee 则是被系统封禁了，我也懒得申诉了。![Screenshot_2023-09-20-15-06-47-649_com.android.browser.jpg](https://github.com/lingeringsound/10007_auto/assets/114198798/36c1b645-c259-43aa-bb98-c499c7cd467e)

**Comment by ChellyL** [comment]
好的，感谢告知，大佬辛苦了
