### ISSUE TITLE
误杀x.com的图片和视频网址twimg.com，请求放行

### ISSUE THREAD

**Issue by Deleted-Account** [lingeringsound/10007_auto#5]
![image](https://github.com/user-attachments/assets/f2e8d94b-b88f-4348-abfa-84eb394e9f4d)

**Comment by lingeringsound** [comment]
好的，谢谢反馈，已经更新了规则了，试试看吧。

**Comment by Deleted-Account** [comment]
> 好的，谢谢反馈，已经更新了规则了，试试看吧。

赞！~

也谢谢你
