### ISSUE TITLE
希望加入 AWAvenue-Ads-Rule 的规则

### ISSUE THREAD

**Issue by walkonbothsides** [lingeringsound/10007_auto#6]
开源地址为 https://github.com/TG-Twilight/AWAvenue-Ads-Rule
体验十分优秀的个人维护规则

**Comment by lingeringsound** [comment]
好的，感谢反馈！

但是我觉得没必要捏，秋风规则，本来就是**极致精简**的类型，喜欢的话，只用秋风的规则就可以了，可以把我这种综合的，容易误杀的删掉。

而且这种和我比较像的主观规则，有些~~误杀他们是不会处理的~~(觉得不是误杀)，我也存在一些你们认为不是误杀，但是我偏要杀的规则。
```
# 例如这个
#百度云升级
127.0.0.1 update.baidu.com
#22.04.22MIUI安装包管理器
127.0.0.1 preview-api.installer.xiaomi.com
127.0.0.1 api.installer.xiaomi.com
```
