### ISSUE TITLE
可以做一个singbox可用的规则集吗

### ISSUE THREAD

**Issue by 82199691** [lingeringsound/10007_auto#7]
可以做一个singbox可用的规则集吗

**Comment by lingeringsound** [comment]
好的，感谢反馈，问题是我不用这些个代理工具去广告，不是很有精力去维护这些规则，到时候格式改了，或者不能用了，误杀了，也不不太可能去修复。

可以去用[秋风规则](https://awavenue.top/Sub.html) 或者 [Adrules](https://awavenue.top/Sub.html) 这些更新都比较积极，维护比较好。

**Comment by 82199691** [comment]
感谢您整理规则，目前我已经fork了您的项目，目前已经支持singbox调用了

**Comment by lingeringsound** [comment]
好的
