### ISSUE TITLE
抱歉大佬打扰了！请问下有办法彻底恢复host吗

### ISSUE THREAD

**Issue by Wizard021** [lingeringsound/10007_auto#8]
之前刷了10007大佬您的去广告模块，卸载后依然会出现b站部分评论区图片无法显示的问题，经过努力终于定位到应该是模块中修改过host的问题，但是我技术有限不知道怎么还原系统host，系统host文件夹也显示没有权限修改，请问有办法将host彻底恢复到安装模块之前的状态吗！非常感谢🙏，我实在是技术有限不知道怎么恢复无奈只能到此求助

**Comment by lingeringsound** [comment]
直接到模块路径修改`/data/adb/modules/GGAT_10007/system/etc/hosts`(**要重启**)，或者用[Adaway](https://github.com/AdAway/AdAway)进行删除和修改。

**Comment by lingeringsound** [comment]
你直接停用模块，也会自动恢复hosts。

**Comment by Wizard021** [comment]
谢谢大佬，模块路径我之前就试过了，但是修改显示无系统权限，停用模块加重启会恢复host吗，我去试一下
